version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-ecr: circleci/aws-ecr@9.0

executors:
  custom-executor:
    docker:
      - image: cimg/aws:2024.03

workflows:
  build_and_push_image:
    triggers:
      - schedule:
          cron: "38 10 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - aws-ecr/build_and_push_image:
          executor: custom-executor
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                aws-access-key-id: AWS_ACCESS_KEY
                aws-secret-access-key: AWS_SECRET_KEY 
          create_repo: false
          extra_build_args: '--compress'
          no_output_timeout: 10m
          path: .circleci
          platform: linux/amd64
          public_registry: false
          push_image: true
          region: ${AWS_DEFAULT_REGION}
          repo: circleci_repo
          repo_encryption_kms_key: arn:aws:kms:us-east-1:730335195561:key/5adca3af-7613-4481-b48f-cadf1b79c637
          repo_encryption_type: KMS
          repo_scan_on_push: true
          set_repo_policy: false
          skip_when_tags_exist: false
          tag: latest,global_ecr